default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix petisco tests
        language: system
        types: [python]
        require_serial: true
        fail_fast: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format petisco tests
        language: system
        types: [python]
        require_serial: true
        fail_fast: true
