repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black petisco tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: flake8
        name: flake8
        entry: flake8 petisco tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true



      - id: isort
        name: isort
        entry: isort petisco tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

