name: ci-macos

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'petisco/VERSION'
      - '.github/ISSUE_TEMPLATE'
      - '.github/workflows/coverage.yml'
    branches: 
      - v1
      - main

jobs:
  ci-macos:

    strategy:
      matrix:
        os: [macOS-latest]
        python-version: ['3.8']
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/*requirements.txt'
      - name: Install dependencies
        run: |
          pip install lume
          lume -install
      - name: Lint - Code checker
        run: lume -lint
      - name: Test
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN_STAGING }}
          SLACK_TESTS_CHANNEL: 'testing'
        run: lume -build -test -test-command-line
