name: ci-macos

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'petisco/VERSION'
      - '.github/workflows/coverage.yml'
    branches: 
      - v1
      - main

jobs:
  ci-macos:

    strategy:
      matrix:
        os: [macOS-latest]
        python-version: [3.8]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install lume
          lume -install
      - name: Lint - Code checker
        run: lume -lint
      - name: Test
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN_STAGING }}
          SLACK_TESTS_CHANNEL: 'testing'
        run: lume -build -test -test-command-line
