name: ci-macos

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'petisco/VERSION'
    branches: 
      - v1
      - master
  push:
    paths-ignore:
      - '*.md'
      - 'petisco/VERSION'
    branches:
      - v1
      - master

jobs:
  ci-macos:

    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest]
        python-version: [3.8]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v1
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install lume
        lume -install
    - name: Lint - Code checker
      run: |
        lume -lint
    - name: Test
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN_STAGING }}
        SLACK_TESTS_CHANNEL: 'testing'
      run: |
        lume -build -test -test-command-line
