name: coverage

on:
  push:
    paths-ignore:
      - '**.md'
      - 'petisco/VERSION'
      - '.github/ISSUE_TEMPLATE'
      - '.github/workflows/ci.yml'
      - '.github/workflows/ci.macos.yml'
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: '**/*requirements.txt'
    - name: Install dependencies
      run: |
        pip install lume
        lume -install
    - name: Coverage
      run: lume -coverage
    - uses: codecov/codecov-action@v2
      with:
        files: cobertura_coverage.xml
        directory: output/coverage/
        name: petisco
        fail_ci_if_error: true
