name: pypi

on:
  release:
    types: [published]

jobs:
  get-version:
    uses: alice-biometrics/actions/.github/workflows/get-version.yml@v1.44
    with:
      type: release
  publish:
    needs: get-version
    uses: alice-biometrics/actions/.github/workflows/publish-pypi.yml@v1.44
    with:
      package_name: petisco
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      username: ${{ secrets.PYPI_TOKEN_USERNAME }}
      password: ${{ secrets.PYPI_TOKEN_PASSWORD_PETISCO }}
      github_access_token: ${{ secrets.PUBLIC_GITHUB_ACCESS_TOKEN }}